[package]
name = "boilr"
version = "0.2.7"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[dependencies]
steam_shortcuts_util = {git="https://github.com/PhilipK/steam_shortcuts_util"}
steamgriddb_api = "^0.2,0"
serde = { version = "^1.0.136", features = ["derive"] }
serde_json = "^1.0.79"
tokio = { version = "^1.17.0", features = ["full"] }
reqwest = { version = "^0.11.10", default_features = false }
config = "^0.11.0"
failure = "^0.1.8"
#https://fltk-rs.github.io/fltk-rs/
fltk = { version = "^1.3.2", features = ["fltk-bundled"], optional = true }
nom = "^7.1.1"
nom_locate = "^4.0.0"
flate2 = "^1.0.22"
toml = { version = "^0.5.8", optional = true }
futures = { version = "^0.3.21" }
dashmap = { version = "^5.2.0", features = ["serde"] }
fltk-theme = {version ="^0.4.2" , optional = true }
is_executable = "^1.0.1"
rusty-leveldb = "^0.3.6"
base64="^0.13.0"

[build-dependencies]
fl2rust = { version = "^0.4", optional = true }

[features]
# default = ["ui"]
ui = ["fltk", "fl2rust", "toml", "fltk-theme"]


[target.'cfg(windows)'.dependencies]
winreg = "0.10.1"
