debug= false

[origin]
enabled = false

[gog]
enabled = false
create_symlinks = true

[epic_games]
enabled = false
create_symlinks = true

[legendary]
enabled = false

[steam]

[itch]
enabled = false
create_symlinks = true

[steamgrid_db]
enabled = true