debug= false

[steamgrid_db]

[origin]
enabled = true

[gog]
enabled = true
create_symlinks = true

[epic_games]
enabled = true
create_symlinks = true

[uplay]
enabled = true

[legendary]
enabled = true

[steam]

[itch]
enabled = true
create_symlinks = true

[steamgrid_db]
enabled = true
prefer_animated = false

[lutris]
enabled = true