name: Release

on:  
  workflow_dispatch:  
    
jobs:
  test_Windows:
    runs-on: windows-latest    
    steps:
    - uses: actions/checkout@v1
    - name: Rust Cache
      id: rust_cache
      uses: Swatinem/rust-cache@v1.3.0
    - name: Build Release      
      run: cargo build --release 
    - name: Bump version and push tag
      id: tag_version
      uses: mathieudutour/github-tag-action@v5.5
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}        
    - name: Compress binaries
      uses: svenstaro/upx-action@v2
      with:
        file: target/release/steam_shortcuts_sync.exe  
    - name: Release
      uses: softprops/action-gh-release@v1      
      with:
        body: ${{ steps.tag_version.outputs.changelog}}
        tag_name: ${{ steps.tag_version.outputs.new_tag}}
        release_name: Release ${{ steps.tag_version.outputs.new_tag}}
        files: |
          target/release/steam_shortcuts_sync.exe
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  test_Linux:
      runs-on: ubuntu-latest    
      steps:
      - uses: actions/checkout@v1
      - name: Rust Cache
        id: rust_cache
        uses: Swatinem/rust-cache@v1.3.0
      - name: Build Release      
        run: cargo build --release 
      - name: Bump version and push tag
        id: tag_version
        uses: mathieudutour/github-tag-action@v5.5
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}   
      - name: Compress binaries
        uses: svenstaro/upx-action@v2
        with:
          file: target/release/steam_shortcuts_sync     
      - name: Release
        uses: softprops/action-gh-release@v1      
        with:
          body: ${{ steps.tag_version.outputs.changelog}}
          tag_name: ${{ steps.tag_version.outputs.new_tag}}
          release_name: Release ${{ steps.tag_version.outputs.new_tag}}
          files: |
            target/release/steam_shortcuts_sync
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
